trigger:
  branches:
    include:
      - master
      - develop
      - release/*
  paths:
    exclude:
      - README.md
      - docs/*

variables:
  dotnetVersion: 2.2.300
  nugetPackPath: './nugetPacks'
  TestProject: '**/Lett.Extensions.Test.csproj'

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: UseDotNet@2
    displayName: '安装 .NET Core sdk'
    inputs:
      packageType: sdk
      version: $(dotnetVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - bash: |
      chmod +x ./build/build.sh
      ./build/build.sh --bootstrap
      ./build/build.sh --target=Test
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    displayName: 执行 cake
