name: 'Build and Test on Ubuntu 16.04'

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  Build-and-Test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: run test
      run: |
        chmod +x ./build/build.sh
        ./build/build.sh --bootstrap
        ./build/build.sh --target=Test
