name: 'Build and Test on macOS X Mojave 10.14'

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  Build-and-Test:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: ‘执行 Cake Task’
        run: |
          ./build/build.sh --bootstrap
          ./build/build.sh --target=Test
