name: 'MacOS 10.14'

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: 执行 Cake
        run: |
          ./build/build.sh --bootstrap
          ./build/build.sh --target=Build
